# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4qWAN_juddDglwm7ZHpZ2i2wVFAn8BG
"""

scores = input().split()
scores = [int(s) for s in scores]
fail_count = sum(1 for s in scores if s < 60)
print(fail_count)