# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y13ralwmPeG_Bk4S9FHXi8wrFWu32CEJ
"""

scores = input().split()
scores = [int(s) for s in scores]
fail_count = sum(1 for s in scores if s < 60)
print(fail_count)

print(max(scores))
print(min(scores))

if len(scores) == 0:
    print(0.0)
else:
    average = sum(scores) / len(scores)
    print(average)